name: Calc first java cs_project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag

    - name: Get Previous tag
      id: previoustag
      uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        
    - name: Get next version
      id: next
      uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
      with:
        version: ${{ steps.previoustag.outputs.tag }}

    - name: Create release
      id: create_release_id
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.next.outputs.version }}
        release_name: Release ${{ steps.next.outputs.version }}

    - uses: actions/checkout@v4
    #- name: Formating 
     # uses: axel-op/googlejavaformat-action@v3
     # with:
     #   args: "--skip-sorting-imports --replace"
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    #- name: Scan security 
    #- uses: github/codeql-action/init@v3
      #with:
      #config-file: ./.github/codeql/codeql-config.yml
      #queries: +security-and-quality,octo-org/python-qlpack/show_ifs.ql@main
      #packs: +scope/pack1,scope/pack2@1.2.3,scope/pack3@4.5.6:path/to/queries
    - name: Build with maven
      run: mvn -B package --file pom.xml
    - name: upload resulting file
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /home/runner/work/javaworld/javaworld/target/External-IP-Checker-1.0.2-jar-with-dependencies.jar
    #- name: Super-linter
    #  uses: super-linter/super-linter@v6.4.0  # x-release-please-version
      # env:
          # To report GitHub Actions status checks
       # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       