name: Calc first java cs_project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        prefix: "v"

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn -B versions:set -DnewVersion=77
    - name: upload resulting file
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /home/runner/work/javaworld/javaworld/target/*
  
 
       