name: Calc first java cs_project
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # required for github-action-get-previous-tag
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      # with:
     #     fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
          #workingDirectory: another/path/where/a/git/repo/is/checked/out # Optional alternative working directory
    #- name: 'Get next minor version'
    #  id: semvers
    #  uses: "WyriHaximus/github-action-next-semvers@v1"
    #  with:
    #      version: ${{ steps.previoustag.outputs.tag }}
    #- name: 'Create new milestone'
    #  id: createmilestone
    #  uses: "WyriHaximus/github-action-create-milestone@v1"
    #  with:
    #      title: ${{ steps.semvers.outputs.patch }}
    #  env:
    #      GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
    #- name: Get next version
    #  id: next
    #  uses: 'WyriHaximus/github-action-next-release-version@1.0.0'
    #  with:
    #      version: ${{ steps.previoustag.outputs.tag }}

    #- name: Create release
    #  id: create_release_id
    #  uses: actions/create-release@v1
    #  env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  with:
    #      tag_name: ${{ steps.next.outputs.version }}
    #      release_name: Release ${{ steps.next.outputs.version }}
    
    #- name: Formating 
     # uses: axel-op/googlejavaformat-action@v3
     # with:
     #   args: "--skip-sorting-imports --replace"
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with maven
      run: mvn -B versions:set -DnewVersion=77
    - name: upload resulting file
      uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: /home/runner/work/javaworld/javaworld/target/*
    #- name: Super-linter
    #  uses: super-linter/super-linter@v6.4.0  # x-release-please-version
      # env:
          # To report GitHub Actions status checks
       # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       